site_name: js2pysecrets
#theme: readthedocs
theme:
  name: material
  custom_dir: docs_source/custom
  icon:
    logo: puzzle
    repo: fontawesome/brands/github
  palette:
    primary: indigo
  features:
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://phpc.social/@poing
      name: poing on phpc.social
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/poing
      name: Brian LaVallee 
    - icon: fontawesome/brands/github 
      link: https://github.com/poing/
      name: Brian LaVallee
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.blocks.html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true

    
plugins:
  - blog:
      post_url_date_format: yyyy-MM-dd
      post_date_format: yyyy-MM-dd
      blog_toc: true
      archive: false
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/poing/JS2PySecrets
repo_name: poing/JS2PySecrets
extra_css:
  - stylesheets/extra.css
docs_dir: docs_source
site_dir: docs
nav:
  - About: index.md
  - API: commands.md
  - gems.md
  - "Contributing to JS2PySecrets":
    - "Getting Started": contributing/index.md
    - "Writing Tests": contributing/tests.md
    - "RNG": contributing/rng.md
  - blog/index.md
  - 'mkdocs.md'
  - 'license.md'
    
