site_name: js2pysecrets
#theme: readthedocs
theme:
  name: material
#  custom_dir: overrides
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
docs_dir: docs_source
site_dir: docs
nav:
    - 'index.md'
    - 'gems.md'
    - 'mkdocs.md'
    - 'license.md'
    